name: SecureVault IPA Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Show Xcode Version
      run: xcodebuild -version

    - name: Build Archive
      run: |
        xcodebuild \
        -project SecureVault.xcodeproj \
        -scheme SecureVault \
        -configuration Release \
        -sdk iphoneos \
        -archivePath $PWD/build/SecureVault.xcarchive \
        archive \
        CODE_SIGNING_ALLOWED=NO

    - name: Export IPA Folder
      run: |
        mkdir -p build/Payload
        cp -R build/SecureVault.xcarchive/Products/Applications/SecureVault.app build/Payload/
        cd build
        zip -r SecureVault.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SecureVault-IPA
        path: build/SecureVault.ipa